"""added identity key column in DetectionRecords

Revision ID: 1dea0fbbd361
Revises: 0f570c6a4041
Create Date: 2024-11-20 01:51:34.289816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dea0fbbd361'
down_revision = '0f570c6a4041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identity_key', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['identity_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('identity_key')

    # ### end Alembic commands ###
