"""updated camera model

Revision ID: 36dc9074e87a
Revises: 55378e818a34
Create Date: 2024-11-28 07:30:26.692304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36dc9074e87a'
down_revision = '55378e818a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rtsp_url', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('cameras_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('cameras_ibfk_1', type_='foreignkey')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('type_id')
        batch_op.drop_column('brand_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ip_address', mysql.VARCHAR(length=15), nullable=False))
        batch_op.create_foreign_key('cameras_ibfk_1', 'camera_brands', ['brand_id'], ['id'])
        batch_op.create_foreign_key('cameras_ibfk_3', 'camera_types', ['type_id'], ['id'])
        batch_op.drop_column('rtsp_url')

    # ### end Alembic commands ###
