"""Group code column, auto fill

Revision ID: 4ad3036334f9
Revises: 5eb47ca01b20
Create Date: 2024-10-06 22:31:41.665310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad3036334f9'
down_revision = '5eb47ca01b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_code', sa.String(length=6), nullable=False))
        batch_op.create_unique_constraint(None, ['group_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('group_code')

    # ### end Alembic commands ###
