"""updated identity key column to Nullable

Revision ID: 55378e818a34
Revises: 1dea0fbbd361
Create Date: 2024-11-20 01:58:30.077313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55378e818a34'
down_revision = '1dea0fbbd361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_records', schema=None) as batch_op:
        batch_op.alter_column('identity_key',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_index('identity_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_records', schema=None) as batch_op:
        batch_op.create_index('identity_key', ['identity_key'], unique=True)
        batch_op.alter_column('identity_key',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
