"""Added CameraTypes and CameraBrands model and updated cascade on groups

Revision ID: 6eecd4688647
Revises: 9bb65c2ecbe2
Create Date: 2024-11-13 15:57:18.539310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6eecd4688647'
down_revision = '9bb65c2ecbe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=False),
    sa.Column('port', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('stream_path', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camera_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.alter_column('ip_address',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.drop_constraint('cameras_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'camera_brands', ['brand_id'], ['id'])
        batch_op.create_foreign_key(None, 'locations', ['location_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'camera_types', ['type_id'], ['id'])

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_constraint('locations_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('locations_ibfk_1', 'groups', ['group_id'], ['id'])

    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cameras_ibfk_1', 'locations', ['location_id'], ['id'])
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('brand_id')
        batch_op.drop_column('type_id')

    op.drop_table('camera_types')
    op.drop_table('camera_brands')
    # ### end Alembic commands ###
