"""Updated detection records added detection status model

Revision ID: 799af551d509
Revises: a153c7cdedda
Create Date: 2024-11-17 19:06:19.623738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '799af551d509'
down_revision = 'a153c7cdedda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('origin_path', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('detected_path', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=False))
        batch_op.alter_column('type_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
        batch_op.create_foreign_key(None, 'detection_status', ['status_id'], ['id'])
        batch_op.drop_column('image_origin_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_origin_path', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
        batch_op.alter_column('type_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('status_id')
        batch_op.drop_column('detected_path')
        batch_op.drop_column('origin_path')
        batch_op.drop_column('confidence')

    # ### end Alembic commands ###
