"""Added FaceImages and UserInfos tables

Revision ID: 92c81f6f65cc
Revises: 78e8cf131c14
Create Date: 2024-11-07 02:38:02.185282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92c81f6f65cc'
down_revision = '78e8cf131c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_key', sa.String(length=255), nullable=False))
        batch_op.drop_index('unique_name')
        batch_op.create_unique_constraint(None, ['unique_key'])
        batch_op.drop_column('unique_name')

    with op.batch_alter_table('group_user', schema=None) as batch_op:
        batch_op.drop_constraint('group_user_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_infos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_infos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('group_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('group_user_ibfk_2', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('face_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('unique_name', ['unique_name'], unique=True)
        batch_op.drop_column('unique_key')

    # ### end Alembic commands ###
