"""Added CASCADE on group_id in group_user

Revision ID: 9ac33d8d358b
Revises: 4ad3036334f9
Create Date: 2024-10-31 18:09:40.755410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac33d8d358b'
down_revision = '4ad3036334f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_user', schema=None) as batch_op:
        batch_op.drop_constraint('group_user_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('group_user_ibfk_1', 'groups', ['group_id'], ['id'])

    # ### end Alembic commands ###
