"""Changed filename to bucket_path

Revision ID: dd80984dcf41
Revises: 92c81f6f65cc
Create Date: 2024-11-10 20:04:16.440756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd80984dcf41'
down_revision = '92c81f6f65cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bucket_path', sa.String(length=255), nullable=False))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('bucket_path')

    # ### end Alembic commands ###
